### PR TITLE
BREAKING: allow to pass an outer yoga provider

### LINKED ISSUE #66: Vite compatibility
Hey,

## The problem 
I was trying to use `@react-three/flex` in a [`vite`](https://vitejs.dev/) based project (instead of the current example that uses CRA) but I landed on multiple issues. 
**EDIT: Actually I fixed it while writing this, so I guess I should still post it for anyone that is in the same situation. 
Scroll to the bottom for the solution. ** 

## Naive installation

```
Uncaught ReferenceError: _a is not defined ... at node_modules/yoga-layout-prebuilt/yoga-layout/dist/entry-browser.js (:3000/node_modules/.vite/@react-three_flex.js?v=63c167e0:27914)
```

Which can be solved either by [replacing the string of the problematic file](https://github.com/facebook/yoga/issues/798#issuecomment-555858987) or by adding `<script>window._a = undefined;</script>` in the index.html

Then there is an issue with `‘@babel/runtime/helpers/esm/extends’`
```
react-dom.development.js:11340 Uncaught TypeError: e[h(...)] is not a function
    at index.js:formatted:1
```

Used in those lines
```
default:
        return e[`set${h(n2)}`](i2);
```

And I couldn't find a solution for that, so I tried looking for issues/PR and stumbled upon this one https://github.com/pmndrs/react-three-flex/pull/37

## yoga wasm PR

Then I 
- added it as package.json dependency with `"react-three-flex": "pmndrs/react-three-flex#37/head"`
- added the corresponding vite.resolve.alias `{ find: "@react-three/flex", replacement: "./node_modules/react-three-flex/src/index.ts" },`
- included it in deps vite `optimizeDeps: { include: ["@react-three/flex"] },`

Which spawns another problem
```
index.js:1 Uncaught (in promise) RuntimeError: abort(RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at z (index.js:1)
    at index.js:1
```

Something that might be worth noting is that this PR seems quite outdated so that might just be the reason (since i'm getting this log `index.js:1 npm install react-three-fiber is deprecated, use @react-three/fiber instead!`)

[repro repository](https://github.com/astahmer/vite-r3flex-issue) here, using the Text component from https://codesandbox.io/embed/7psew

## Solution 
**EDIT: follow the steps from the `yoga wasm PR` section and then add  [this file](https://github.com/pmndrs/react-three-flex/blob/0d9c7d8a76b5d70263af873da8f25c9632dd2f0c/examples/public/yoga.wasm) in /public/yoga.wasm  **

### PR DESCRIPTION
**Pull request by saitonakamura**
Disclaimer: my original idea was to just replace `yoga-layout-prebuilt` with `yoga-layout-wasm` (like #67 or #37 ), but my experements proved importing wasm files and using  `yoga-layout-wasm` in general is not easy task and requires configuring userland bundler, hurting the UX. For instance, I experienced cryptic webpack errors in storybook, vite tried to prebuild the wasm file instead of importing it as a url and so on. So I decided that if we can provide a way to pass a outer yoga runtime while still having the ability to use vanilla `yoga-layout-prebuilt` experience -- that's the right way

This is mainly to allow usage of yoga-layout-wasm. From now on there's 2 entrpoints,
a default one with YogaPrebuiltProvider (which uses yoga-layout-prebuilt)
and outerRuntime that exports YogaProvider that allows to pass an arbitrary runtime
(that conforms with Yoga types)

This is a breaking change because library users will have to place a YogaProvider/YogaPrebuiltProvider in their code

Fixes #66

### CODE REVIEW

**Comment by saitonakamura** [comment]
I tried to come up with a way that doesn't require current users to mandatory use a provider if they are fine with `yoga-layout-prebuilt`. There's one, however it complicates the code too much IMO so I don't like it, but here it is

Instead of calling useYoga inside Flex and Box, allow to accept yoga as a prop
Then on an entrypoint level provide wrappers that either import `yoga-layout-prebuilt` (vanilla) or get the value from the provider (wasm experience). Probably will look like

index.tsx
```ts
import { Flex: FlexImpl, FlexProps } from './Flex
import Yoga from 'yoga-layout-prebuilt'

export const Flex = (props: FlexProps) => <FlexImpl yoga={Yoga} {...props} />
```

outerRuntime.tsx
```ts
import { Flex: FlexImpl, FlexProps } from './Flex
import { useYoga } from './hooks'

export const Flex = (props: FlexProps) => {
  const Yoga = useYoga()
  return <FlexImpl yoga={Yoga} {...props} />
}
```

**Comment by saitonakamura** [comment]
@astahmer wasm experience will work like this

https://github.com/pmndrs/react-three-flex/pull/69/files#diff-dcf2f90bea62971aab7c1d7b44c7cb1ac0697e2ea9f52c134251ba20b68d370bR4-R13

```ts
import YogaWasmFile from 'yoga-layout-wasm/dist/yoga.wasm?url' // ?url this a vite thing to force file-loader

function App() {
  const initYoga = useCallback(() => Yoga.init(YogaWasmFile), [])

  return (
    <YogaProvider initYoga={initYoga}>
      {...}
    </YogaProvider>
  )
}
```

**Comment by drcmda** [comment]
will it making it easier if we host the yoga wasm? that's how useGLTF with draco currently works. the binary is hosted by google in that case and it's usually pre-cached by the browser. we do give users the ability to self host, in which case they'll have to put binaries into /public and the loader then merely xhr-fetches them.

**Comment by saitonakamura** [comment]
It will, but only partly. It will help with settings up file-loader style of wasm file import (there was a problem with because it tries to [precompile wasm files](https://vitejs.dev/guide/features.html#webassembly)), for other bundles it's just a chore (but can be tricky if certain framework isn't flexible enough, create-react-app for instance).

But that's only one side of a coin, another side is that yoga-layout-wasm js glue tries to import `path` and `fs` for some reason, it's even somewhat [mentioned in the docs](https://github.com/pinqy520/yoga-layout-wasm#webpack-and-auto-fallback), but trying to set it to false with webpack lead me to webpack complaining that it should be a string

Because of the latter issue I couldn't set `yoga-layout-wasm` up in neither of bundlers expect vite (I tried webpack and esbuild). And simultaneously, vite is the only one that can't use `yoga-layout-prebuilt`. I mean, it's basically a mess so that led me to idea that since there's no one-size-fits-all yoga js bindings, I'm essentially exposing a way to pass an outer runtime

I'll be trying to write my own wasm binding for yoga, maybe even without emscripten, but I'm pretty sure that's gonna take a long time so...

**Pull request closed without merging**
